### ISSUE TITLE
removal of the existing RabbitMQ

### ISSUE THREAD

**Issue by CRTISIT** [rockfordlhotka/Cloud-Native-HOL#51]
I noticed you updated the labs to have a lab04 and lab05. Thats awesome. Will be looking at it tonight for sure.

Since I wanted to leave as much of my environment still running as possible on my computer (havent rebooted or anything yet), until I can finish this training class, can you explain what needs to be done to my Windows 10 computer (as far as undoing enough of the last steps - in order to start with a clean slate - for the new LAB04. That way I could just erase what is needed for the old RabbitMQ, and leave everything else in place (if thats possible) and just pickup where I left off before starting with the RabbitMQ stuff.

Let me know. Thanks!

**Comment by rockfordlhotka** [comment]
Related to #48
