### ISSUE TITLE
Steps to create the solution?

### ISSUE THREAD

**Issue by CRTISIT** [rockfordlhotka/Cloud-Native-HOL#52]
We ran out of time in the class, but you had mentioned you would try to show the steps you took to create the final solution in Visual Studio.  If possible, could you post something here in a wiki page or another readme file about how you did that with Visual Studio 2019?  IT would be super helpful to see how you did that!

**Comment by rockfordlhotka** [comment]
You should be able to open the Lab03/End solution to see how it is put together.
